### ISSUE TITLE
Replace System.CommandLine with something better

### ISSUE THREAD

**Issue by rgwood** [rgwood/RezoningScraper#5]
I don't much like System.CommandLine:

- As of [Beta 2](https://github.com/dotnet/command-line-api/issues/1537) there is a ton of boilerplate required
- [It takes over exception handling](https://github.com/dotnet/command-line-api/issues/796) and this makes Sentry exception logging difficult

Alternatives to investigate:
- [Cocona](https://github.com/mayuki/Cocona)
- [CliFX](https://github.com/Tyrrrz/CliFx)
- [Command Line Parser](https://github.com/commandlineparser/commandline)

**Comment by rgwood** [comment]
Switched to Cocona. Takes over exception handling but I like its ergonomics.

**Comment by perlun** [comment]
@rgwood Thanks for the suggestion about Cocona. It seems way, way simpler than `System.CommandLine` in fact, but still with a nice feature set.
